name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov textblob

      - name: Run basic tests
        run: |
          python -c "import sys; print(f'Python {sys.version}')"
          pytest -v          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install pytest pytest-cov textblob
          fi

      - name: Download TextBlob corpora (best-effort)
        run: |
          # TextBlob may require NLTK corpora for some features. This step is best-effort and
          # will not fail the job if the download fails.
          python -m textblob.download_corpora || true

      - name: Run tests with coverage
        run: |
          mkdir -p reports
          pytest --maxfail=1 -q --junitxml=reports/junit.xml --cov=sentiment --cov-report=xml:reports/coverage.xml

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: reports

      - name: Upload pytest log (optional)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-log
          path: .

      - name: Show summary
        if: success()
        run: |
          echo "Tests passed on Python ${{ matrix.python-version }}"
          
